### ISSUE TITLE
Screen is not working 

### ISSUE THREAD

**Issue by MinaGabriel** [adafruit/Adafruit_Python_CharLCD#20]
My screen doesn't show test, when i run the code it just turn the background light ON - GPIO 4-  I'm not sure if something with the wires or the LCD itself is bad? is there is a way to test what's wrong? 

Thanks 
[http://content.screencast.com/users/minagabriel/folders/Snagit/media/83d6748b-7219-4cfb-b3e7-f53c8f905112/2016-05-17_10-59-05.png](url)

**Comment by ladyada** [comment]
if you purchased it from adafruit, post in the forums for support. tech support is not done in github issues
