### ISSUE TITLE
Language Porting Info

### ISSUE THREAD

**Issue by TheNotary** [adafruit/Adafruit_Python_CharLCD#7]
Hey, I'm coming here from this product page http://www.adafruit.com/products/1115

Then to https://learn.adafruit.com/character-lcd-with-raspberry-pi-or-beaglebone-black/usage

And finally I'm here.  So this uses Python.  I'm going to add this to a ruby project, so I feel like I should use the ruby equivalent to this library to minimize the number of languages involved.  It seems as though the ruby equivalent doesn't exist yet though.  Correct me if I'm wrong, but to get the ruby equivelent I'd more or less just need to do a lot of copy and pasting (and do minor syntax editing) from this repo and also this Adafruit_Python_GPIO library https://github.com/adafruit/Adafruit_Python_GPIO and then call it a day, right?  It seems odd that I would be the first to do that, so maybe I'm missing something??  If any repo watchers know of other libraries involved in the i2c chip used in the LCD that I should know about, I'd love to hear about it, and maybe the extra link/info should go into one of the repos so others know.

**Comment by tdicola** [comment]
Oh nice, thanks for checking out the library!  I don't know of a ruby version either, but if you implement one I'd be happy to mention it in the Raspberry Pi character LCD guide so folks might find it.

If it helps too you might not really have to port the whole Python GPIO library over to ruby.  That library is used as a layer to abstract away platform-specific GPIO libraries like RPi.GPIO on the Pi or BBIO on the BeagleBone Black.  If ruby only has a GPIO library for the Pi then you might not worry about porting over the Python GPIO library and instead just make a library with the same interface but that calls the appropriate ruby Pi GPIO library.  I'm not super familiar with what GPIO libraries are around for ruby but I bet you can find some good pointers to them from searching around.

Thanks for checking out the library and let me know if you do make a ruby version that Pi users can use too.
